### ISSUE TITLE
gfitsio-create-img function creates two headers

### ISSUE THREAD

**Issue by DBernardes** [USNavalResearchLaboratory/GFITSIO#3]
Hi, 
I am using the GFITSIO package to create fits images. 
However, when using the gfitsio-create-img function, the image is created with two headers.
Is there a way to fix this?

**Comment by gatling-nrl** [comment]
The primary header/image has to be created when the file is created. So create-img is always going to be creating the secondary headers. If you really want to only have the primary header, you should be able to set the size of the primary and then write to it, without calling create-img. Note the primary header has to always be an image and can't be a table.

**Comment by DBernardes** [comment]
It worked.
Thanks!
